### ISSUE TITLE
Build with ghc 8.4?

### ISSUE THREAD

**Issue by erikd** [bitemyapp/esqueleto#88]
Esqueleto version 2.5.3 doesn't build with ghc 8.4, due to `Semigroup` becoming a superclass of `Monoid`:
```
src/Database/Esqueleto/Internal/Sql.hs:115:10: error:
    • No instance for (Semigroup SideData)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid SideData’
    |
115 | instance Monoid SideData where
    |          ^^^^^^^^^^^^^^^
```

**Comment by k-bx** [comment]
@erikd put this in your `extra-deps` section of `stack.yaml`:

```
- git: https://github.com/bitemyapp/esqueleto.git
  commit: b81e0d951e510ebffca03c5a58658ad884cc6fbd
```

@bitemyapp a hackage release would be much appreciated

**Comment by bitemyapp** [comment]
@k-bx it's not ready for release. Stated elsewhere that I wanted it to conform in a type-safe way with the Read/Write roles in Persistent. That work and the associated tests are not done yet.

**Comment by bitemyapp** [comment]
@ilovezfs I need to add some tests but the foundation of what I needed to do is there. I'll make sure I incorporate GHC 8.4 compat into the next release.

**Comment by ilovezfs** [comment]
any update here on when the next release may be?

**Comment by parsonsmatt** [comment]
Closing as duplicate of #89 and #109
