### ISSUE TITLE
esqueleto-2.5.3 does not compile with GHC 8.4.1

### ISSUE THREAD

**Issue by peti** [bitemyapp/esqueleto#77]
The error is:

~~~
src/Database/Esqueleto/Internal/Sql.hs:115:10: error:
    • No instance for (Semigroup SideData)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid SideData’
    |
115 | instance Monoid SideData where
    |          ^^^^^^^^^^^^^^^

src/Database/Esqueleto/Internal/Sql.hs:118:15: error:
    • No instance for (Semigroup DistinctClause)
        arising from a use of ‘<>’
    • In the first argument of ‘SideData’, namely ‘(d <> d')’
      In the expression:
        SideData
          (d <> d')
          (f <> f')
          (s <> s')
          (w <> w')
          (g <> g')
          (h <> h')
          (o <> o')
          (l <> l')
          (k <> k')
      In an equation for ‘mappend’:
          SideData d f s w g h o l k `mappend` SideData d'
                                                        f'
                                                        s'
                                                        w'
                                                        g'
                                                        h'
                                                        o'
                                                        l'
                                                        k'
            = SideData
                (d <> d')
                (f <> f')
                (s <> s')
                (w <> w')
                (g <> g')
                (h <> h')
                (o <> o')
                (l <> l')
                (k <> k')
    |
118 |     SideData (d <> d') (f <> f') (s <> s') (w <> w') (g <> g') (h <> h') (o <> o') (l <> l') (k <> k')
    |               ^^^^^^^

src/Database/Esqueleto/Internal/Sql.hs:118:45: error:
    • No instance for (Semigroup WhereClause)
        arising from a use of ‘<>’
    • In the fourth argument of ‘SideData’, namely ‘(w <> w')’
      In the expression:
        SideData
          (d <> d')
          (f <> f')
          (s <> s')
          (w <> w')
          (g <> g')
          (h <> h')
          (o <> o')
          (l <> l')
          (k <> k')
      In an equation for ‘mappend’:
          SideData d f s w g h o l k `mappend` SideData d'
                                                        f'
                                                        s'
                                                        w'
                                                        g'
                                                        h'
                                                        o'
                                                        l'
                                                        k'
            = SideData
                (d <> d')
                (f <> f')
                (s <> s')
                (w <> w')
                (g <> g')
                (h <> h')
                (o <> o')
                (l <> l')
                (k <> k')
    |
118 |     SideData (d <> d') (f <> f') (s <> s') (w <> w') (g <> g') (h <> h') (o <> o') (l <> l') (k <> k')
    |                                             ^^^^^^^

src/Database/Esqueleto/Internal/Sql.hs:118:55: error:
    • No instance for (Semigroup GroupByClause)
        arising from a use of ‘<>’
    • In the fifth argument of ‘SideData’, namely ‘(g <> g')’
      In the expression:
        SideData
          (d <> d')
          (f <> f')
          (s <> s')
          (w <> w')
          (g <> g')
          (h <> h')
          (o <> o')
          (l <> l')
          (k <> k')
      In an equation for ‘mappend’:
          SideData d f s w g h o l k `mappend` SideData d'
                                                        f'
                                                        s'
                                                        w'
                                                        g'
                                                        h'
                                                        o'
                                                        l'
                                                        k'
            = SideData
                (d <> d')
                (f <> f')
                (s <> s')
                (w <> w')
                (g <> g')
                (h <> h')
                (o <> o')
                (l <> l')
                (k <> k')
    |
118 |     SideData (d <> d') (f <> f') (s <> s') (w <> w') (g <> g') (h <> h') (o <> o') (l <> l') (k <> k')
    |                                                       ^^^^^^^

src/Database/Esqueleto/Internal/Sql.hs:118:85: error:
    • No instance for (Semigroup LimitClause)
        arising from a use of ‘<>’
    • In the 8th argument of ‘SideData’, namely ‘(l <> l')’
      In the expression:
        SideData
          (d <> d')
          (f <> f')
          (s <> s')
          (w <> w')
          (g <> g')
          (h <> h')
          (o <> o')
          (l <> l')
          (k <> k')
      In an equation for ‘mappend’:
          SideData d f s w g h o l k `mappend` SideData d'
                                                        f'
                                                        s'
                                                        w'
                                                        g'
                                                        h'
                                                        o'
                                                        l'
                                                        k'
            = SideData
                (d <> d')
                (f <> f')
                (s <> s')
                (w <> w')
                (g <> g')
                (h <> h')
                (o <> o')
                (l <> l')
                (k <> k')
    |
118 |     SideData (d <> d') (f <> f') (s <> s') (w <> w') (g <> g') (h <> h') (o <> o') (l <> l') (k <> k')
    |                                                                                     ^^^^^^^

src/Database/Esqueleto/Internal/Sql.hs:127:10: error:
    • No instance for (Semigroup DistinctClause)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid DistinctClause’
    |
127 | instance Monoid DistinctClause where
    |          ^^^^^^^^^^^^^^^^^^^^^

src/Database/Esqueleto/Internal/Sql.hs:180:10: error:
    • No instance for (Semigroup WhereClause)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid WhereClause’
    |
180 | instance Monoid WhereClause where
    |          ^^^^^^^^^^^^^^^^^^

src/Database/Esqueleto/Internal/Sql.hs:190:10: error:
    • No instance for (Semigroup GroupByClause)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid GroupByClause’
    |
190 | instance Monoid GroupByClause where
    |          ^^^^^^^^^^^^^^^^^^^^

src/Database/Esqueleto/Internal/Sql.hs:204:10: error:
    • No instance for (Semigroup LimitClause)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid LimitClause’
    |
204 | instance Monoid LimitClause where
    |          ^^^^^^^^^^^^^^^^^^
~~~

**Comment by parsonsmatt** [comment]
Closing as duplicate of #89 and #109
